name: Simple Start Up
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Build my Virtual OS
    runs-on: Ubuntu-latest
    steps:
    - name: checkout my codes
      uses: actions/checkout@v2
    - name: Print and list out content
      run: |
        ls
        echo Hello there!
    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: lowkh/hiddenWeek7
        token: ${{ secrets.WEEK7 }} 
    - name: List contents
      run: |
        ls
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python my_script.py
    - name: install plugin
      run: |
        pip install pytest pytest-cov
        pytest --cov
