name: Simple Start Up
on:
  push:
    branches: [main]
    
jobs:
  build:
    name: Build my Virtual OS
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: install plugin
      run: |
        pip install pytest pytest-cov

    - name: checkout my codes
      uses: actions/checkout@v4
      with:
        repository: lowkh/CI_Demo_T01_2023

    - name: Checkout private repo
      uses: actions/checkout@v4
      with:
        repository: lowkh/hiddenWeek7
        token: ${{ secrets.WEEK7 }} 
        path: hiddenCode

    - name: list current files
      run: |
        ls
        sudo mv *.* ./hiddenCode
        ls
